on: push
name: Check Allowed Files
jobs:
  check:
    runs-on: self-hosted
    container:
      image: ghcr.io/statprog-s1-2020/hw2-docker:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Files
      run: |
        checklist::quit_on_failure({
          checklist::check_allowed_files(
            c("hw2.Rmd", "hw2.Rproj", "README.md", "data/*")
          )
        })
      shell: Rscript {0}
